export const ON_AUTH_INIT = 'ON_AUTH_INIT';
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const ON_AUTH = "ON_AUTH";
export const ON_REGISTER = "ON_REGISTER";
export const ON_REGISTRATION_FAILED = 'ON_REGISTRATION_FAILED';
export const UPDATING_PROFILE = 'UPDATING_PROFILE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';

export const PREPARE_CALLER = 'PREPARE_CALLER';
export const CALL_INIT = 'CALL_INIT';
export const CALL_ACCEPTED = 'CALL_ACCEPTED';
export const CALL_REJECTED = 'CALL_REJECTED';
export const ON_TRACK = 'ON_TRACK';
export const ON_LOCAL_STREAM = 'ON_LOCAL_STREAM';
export const ON_INCOMING_CALL = 'ON_INCOMING_CALL';
export const END_CALL = 'END_CALL';
export const ON_ERROR = 'ON_ERROR';

export const CHAT_INIT_SUCCESS = 'CHAT_INIT_SUCCESS';
export const ON_ROOMS_LOADED = 'ON_ROOMS_LOADED';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const ON_NEW_MESSAGE = 'ON_NEW_MESSAGE';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';
export const START_NEW_CHAT_SUCCESS = 'START_NEW_CHAT_SUCCESS';
export const START_NEW_CHAT_FAILED = 'START_NEW_CHAT_FAILED';
export const ON_ROOMS_FETCHED = 'ON_ROOMS_FETCHED';
export const DELETE_CHAT = 'DELETE_CHAT';
export const JOIN_ROOM = 'JOIN_ROOM';
export const SUBSCRIPTION_SUCCESSFUL = 'SUBSCRIPTION_SUCCESSFUL';
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const ON_CHAT_REQUEST = 'ON_CHAT_REQUEST';
export const ON_ACCEPT_CHAT_REQUEST = 'ON_ACCEPT_CHAT_REQUEST';
export const ON_DENY_CHAT_REQUEST = 'ON_DENY_CHAT_REQUEST';
export const CHAT_REQUEST_ACCEPTED = 'CHAT_REQUEST_ACCEPTED';
export const CHAT_REQUEST_DENIED = 'CHAT_REQUEST_DENIED';

export const ON_NEW_NOTIFICATION = 'ON_NEW_NOTIFICATION';


export const RESET_FIELDS = 'RESET_FIELDS'; 